name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Step to clear Git credentials
      #- name: Clear Git credentials
      #  run: git credential reject

      # Step to clean Git configuration
      - name: Clean Git configuration
        run: git config --global --unset http.https://github.com/.extraheader

      # Step to set CI to false
      - name: Get Date
        id: get-date
        run: |
          echo "setOutPut name=date::$(/bin/date -u "+%Y%m%d")"
          echo "CI=false"
        shell: bash

      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
